import Config

config :school_house,
  redirects: %{
    ~r/^\/$/E => "/en",
    ~r/lessons\/basics\/pattern-matching\/?$/E => "lessons/basics/pattern_matching",
    ~r/lessons\/basics\/control-structures\/?$/E => "lessons/basics/control_structures",
    ~r/lessons\/basics\/pipe-operator\/?$/E => "lessons/basics/pipe_operator",
    ~r/lessons\/basics\/date-time\/?$/E => "lessons/basics/date_time",
    ~r/lessons\/basics\/mix-tasks\/?$/E => "lessons/intermediate/mix_tasks",
    ~r/lessons\/basics\/iex-helpers\/?$/E => "lessons/basics/iex_helpers",
    ~r/lessons\/basics\/testing\/?$/E => "lessons/testing/basics",
    ~r/lessons\/advanced\/erlang\/?$/E => "lessons/intermediate/erlang",
    ~r/lessons\/advanced\/error-handling\/?$/E => "lessons/intermediate/error_handling",
    ~r/lessons\/advanced\/escripts\/?$/E => "lessons/intermediate/escripts",
    ~r/lessons\/advanced\/concurrency\/?$/E => "lessons/intermediate/concurrency",
    ~r/lessons\/advanced\/otp-concurrency\/?$/E => "lessons/advanced/otp_concurrency",
    ~r/lessons\/advanced\/otp-supervisors\/?$/E => "lessons/advanced/otp_supervisors",
    ~r/lessons\/advanced\/otp-distribution\/?$/E => "lessons/advanced/otp_distribution",
    ~r/lessons\/advanced\/umbrella-projects\/?$/E => "lessons/advanced/umbrella_projects",
    ~r/lessons\/advanced\/gen-stage\/?$/E => "lessons/data_processing/genstage",
    ~r/lessons\/ecto\/querying\/?$/E => "lessons/ecto/querying_basics",
    ~r/lessons\/specifics\/plug\/?$/E => "lessons/misc/plug",
    ~r/lessons\/specifics\/eex\/?$/E => "lessons/misc/eex",
    ~r/lessons\/specifics\/ets\/?$/E => "lessons/storage/ets",
    ~r/lessons\/specifics\/mnesia\/?$/E => "lessons/storage/mnesia",
    ~r/lessons\/specifics\/debugging\/?$/E => "lessons/misc/debugging",
    ~r/lessons\/specifics\/nerves\/?$/E => "lessons/misc/nerves",
    ~r/lessons\/libraries\/guardian\/?$/E => "lessons/misc/guardian",
    ~r/lessons\/libraries\/poolboy\/?$/E => "lessons/misc/poolboy",
    ~r/lessons\/libraries\/benchee\/?$/E => "lessons/misc/benchee",
    ~r/lessons\/libraries\/bypass\/?$/E => "lessons/testing/bypass",
    ~r/lessons\/libraries\/distillery\/?$/E => "lessons/misc/distillery",
    ~r/lessons\/libraries\/stream-data\/?$/E => "lessons/testing/stream_data",
    ~r/lessons\/libraries\/nimble-publisher\/?$/E => "lessons/misc/nimble_publisher",
    ~r/lessons\/libraries\/mox\/?$/E => "lessons/testing/mox",
    ~r/^\/cb/E => "/zh-hans",
    ~r/^\/tw/E => "/zh-hant",
    ~r/^\/my/E => "/me",
    ~r/^\/jp/E => "/ja",
    ~r/^\/gr/E => "/el"
  }
